from __future__ import annotations

import base64
import hashlib
import json
from dataclasses import dataclass
from io import BytesIO
from pathlib import PurePosixPath
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo

from cutsceneai_performance import (
    PerformanceBundle,
    load_performance_bundle,
    render_performance_bundle,
)
from pydantic import BaseModel

from .models import UnityExportPlan
from .native_models import UnityNativeRealizationTarget
from .performance import compile_performance_bundle
from .performance_models import UnityPerformanceMapping
from .serialization import (
    render_unity_performance_mapping,
    render_unity_plan,
)

UNITY_NATIVE_EDITOR_SCRIPT_FILENAME = "CutSceneAIGeneratedPerformance.cs"
UNITY_NATIVE_RUNNER_FILENAME = "run-unity-native.ps1"
_ZIP_TIMESTAMP = (1980, 1, 1, 0, 0, 0)


@dataclass(frozen=True)
class UnityNativePerformancePackage:
    bundle: PerformanceBundle
    plan: UnityExportPlan
    mapping: UnityPerformanceMapping
    target: UnityNativeRealizationTarget


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _mapping_target_root(mapping: UnityPerformanceMapping) -> str:
    marker = "/Body/"
    path = mapping.body_tracks[0].target_animation_path
    if marker not in path:
        raise ValueError(
            "Unity body target path does not contain the required Body folder."
        )
    return path.split(marker, 1)[0]


def compile_unity_native_performance_package(
    bundle: PerformanceBundle,
    *,
    plan: UnityExportPlan,
    mapping: UnityPerformanceMapping,
    target: UnityNativeRealizationTarget,
) -> UnityNativePerformancePackage:
    """Validate one unchanged bundle and its explicit Unity native target."""

    rendered_bundle = render_performance_bundle(bundle)
    verified_bundle = load_performance_bundle(rendered_bundle)
    expected_mapping = compile_performance_bundle(
        verified_bundle,
        export_plan=plan,
        target_path=_mapping_target_root(mapping),
    )
    if mapping != expected_mapping:
        raise ValueError(
            "Unity performance mapping is not the deterministic mapping of the bundle."
        )
    rendered_mapping = render_unity_performance_mapping(mapping).encode("utf-8")
    if target.source_mapping_sha256 != _sha256(rendered_mapping):
        raise ValueError("Unity native target does not match the mapping SHA-256.")
    if target.project_id != mapping.project_id or plan.project_id != mapping.project_id:
        raise ValueError(
            "Unity native target, plan, and mapping use different projects."
        )
    sequence = plan.sequences[0]
    if (
        target.timeline_asset_path != sequence.timeline_asset_path
        or target.scene_asset_path != sequence.scene_asset_path
        or mapping.source_scene_id != sequence.source_scene_id
    ):
        raise ValueError("Unity native target paths or scene do not match the plan.")

    actor_targets = {item.actor_binding_id: item for item in target.actors}
    expected_actor_ids = {item.actor_binding_id for item in mapping.body_tracks} | {
        item.actor_binding_id for item in mapping.facial_tracks
    }
    if set(actor_targets) != expected_actor_ids:
        raise ValueError(
            "Unity native target actors do not exactly match generated body and face tracks."
        )
    plan_actors = {item.binding_id: item for item in sequence.actors}
    if set(actor_targets) - set(plan_actors):
        raise ValueError("Unity native target references an unknown plan actor.")
    for binding_id, native_target in actor_targets.items():
        actor = plan_actors[binding_id]
        if actor.placeholder or actor.prefab_path != native_target.prefab_path:
            raise ValueError(
                "Unity native target requires the same non-placeholder prefab as the plan."
            )

    return UnityNativePerformancePackage(
        bundle=verified_bundle,
        plan=plan.model_copy(deep=True),
        mapping=mapping.model_copy(deep=True),
        target=target.model_copy(deep=True),
    )


def _encoded_json(value: object) -> str:
    if isinstance(value, BaseModel):
        value = value.model_dump(mode="json")
    data = json.dumps(value, separators=(",", ":"), sort_keys=True).encode("utf-8")
    return base64.b64encode(data).decode("ascii")


_UNITY_NATIVE_TEMPLATE = r"""// Generated by CutSceneAI Unity Adapter v0.1.0 for Unity 6000.0.
// Copy only through the generated runner. The importer refuses every asset conflict.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using UnityEditor;
using UnityEditor.PackageManager;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.SceneManagement;
using UnityEngine.Timeline;

public static class CutSceneAIGeneratedPerformance
{
    private const string PlanBase64 = "__PLAN_BASE64__";
    private const string MappingBase64 = "__MAPPING_BASE64__";
    private const string TargetBase64 = "__TARGET_BASE64__";
    private const string BodyPrefix = "CSA|BODY|";
    private const string FacePrefix = "CSA|FACIAL|";
    private const string CameraMotionPrefix = "CSA|CAMERA-MOTION|";
    private const string CameraPrefix = "CSA|CAMERA|";
    private const string AudioPrefix = "CSA|AUDIO|";
    private const string ActorPrefix = "CSA|ACTOR|";

    [Serializable] private sealed class VectorValue { public float x; public float y; public float z; }
    [Serializable] private sealed class QuaternionValue { public float x; public float y; public float z; public float w; }
    [Serializable] private sealed class Artifact { public string sha256; }
    [Serializable] private sealed class JointBinding { public string target_human_bone; }
    [Serializable] private sealed class BodyKeyframe { public int timeline_frame; public VectorValue root_position_m; public QuaternionValue[] joint_rotations; }
    [Serializable] private sealed class BodyTrack {
        public string semantic_id; public string actor_binding_id; public int start_frame;
        public int end_frame; public string target_animation_path; public Artifact source_artifact;
        public JointBinding[] joint_bindings; public BodyKeyframe[] keyframes;
    }
    [Serializable] private sealed class CurveBinding { public string target_blendshape_name; }
    [Serializable] private sealed class FaceKeyframe { public int timeline_frame; public float[] weights; }
    [Serializable] private sealed class FaceTrack {
        public string semantic_id; public string actor_binding_id; public int start_frame;
        public int end_frame; public string target_animation_path; public Artifact source_artifact;
        public CurveBinding[] curve_bindings; public FaceKeyframe[] keyframes;
    }
    [Serializable] private sealed class CameraKeyframe { public int timeline_frame; public VectorValue position_m; public QuaternionValue rotation; public float focal_length_mm; }
    [Serializable] private sealed class CameraTrack {
        public string semantic_id; public string camera_binding_id; public string source_camera_cut_id;
        public int start_frame; public int end_frame; public string target_animation_path;
        public float sensor_width_mm; public float sensor_height_mm; public Artifact source_artifact;
        public CameraKeyframe[] keyframes;
    }
    [Serializable] private sealed class AudioTrack {
        public string dialogue_cue_id; public string actor_binding_id; public int start_frame;
        public int end_frame; public string target_audio_path; public Artifact source_artifact;
    }
    [Serializable] private sealed class Mapping {
        public string project_id; public string source_scene_id; public string source_bundle_sha256;
        public int fps; public int duration_frames; public BodyTrack[] body_tracks;
        public FaceTrack[] facial_tracks; public CameraTrack[] camera_tracks; public AudioTrack[] audio_tracks;
    }
    [Serializable] private sealed class ActorTarget {
        public string actor_binding_id; public string prefab_path; public string animator_path;
        public string facial_renderer_path;
    }
    [Serializable] private sealed class RenderTarget { public int width; public int height; public string output_directory; }
    [Serializable] private sealed class Target {
        public string project_id; public string source_mapping_sha256; public string timeline_asset_path;
        public string scene_asset_path; public ActorTarget[] actors; public RenderTarget render;
    }
    [Serializable] private sealed class Plan {
        public string adapter_version; public string project_id; public int fps;
        public TimelineSemantics semantics; public ScenePlan[] sequences;
    }
    [Serializable] private sealed class ScenePlan { public string source_scene_id; public int duration_frames; public ActorPlan[] actors; }
    [Serializable] private sealed class ActorPlan {
        public string binding_id; public string display_name; public TransformValue transform;
    }
    [Serializable] private sealed class TransformValue {
        public VectorValue position_m; public QuaternionValue rotation; public VectorValue scale;
    }
    [Serializable] private sealed class TimelineSemantics {
        public string semantics_version; public string cir_schema_version;
        public string cir_fingerprint_sha256; public string project_id; public int fps;
        public SemanticScene[] scenes;
    }
    [Serializable] private sealed class SemanticScene {
        public string source_scene_id; public int duration_frames; public SemanticEntity[] entities;
        public SemanticPerformance[] performance_cues; public SemanticDialogue[] dialogue_cues;
        public SemanticCamera[] camera_cuts;
    }
    [Serializable] private sealed class SemanticEntity { public string binding_id; public string source_entity_id; public string kind; }
    [Serializable] private sealed class SemanticPerformance {
        public string cue_id; public string source_beat_id; public string actor_binding_id;
        public int start_frame; public int end_frame; public string motion_intent_sha256;
        public string look_at_binding_id;
    }
    [Serializable] private sealed class SemanticDialogue {
        public string cue_id; public string source_beat_id; public string actor_binding_id;
        public int start_frame; public int window_end_frame; public string text_sha256; public string language;
    }
    [Serializable] private sealed class SemanticCamera {
        public string cut_id; public string source_shot_id; public string[] source_beat_ids;
        public int start_frame; public int end_frame; public string purpose; public string framing;
        public string angle; public string movement; public float lens_mm;
        public string[] subject_binding_ids; public string[] target_binding_ids;
    }
    [Serializable] private sealed class RealizedSection {
        public string semantic_id; public string actor_binding_id; public string asset_ref;
        public int start_frame; public int end_frame; public bool placeholder;
    }
    [Serializable] private sealed class ReadbackEvidence {
        public RealizedSection[] animation_sections; public RealizedSection[] facial_sections;
        public RealizedSection[] camera_sections; public RealizedSection[] audio_sections;
    }
    [Serializable] private sealed class EngineReadback {
        public string readback_version; public string engine; public string engine_version;
        public string adapter_version; public string timeline_asset; public TimelineSemantics semantics;
        public ReadbackEvidence evidence; public string[] warnings;
    }
    [Serializable] private sealed class RenderedFrame { public int frame; public string relative_path; public string sha256; }
    [Serializable] private sealed class RenderManifest {
        public string manifest_version; public string engine; public string source_bundle_sha256;
        public int expected_frame_count; public int rendered_frame_count; public RenderedFrame[] frames;
    }
    [Serializable] private sealed class Lifecycle {
        public string lifecycle_version; public int import_process_id; public int readback_process_id;
        public bool import_completed; public bool saved; public bool restarted;
        public bool readback_completed; public bool render_completed; public string[] errors;
    }

    private static Plan LoadPlan() => Load<Plan>(PlanBase64, "plan");
    private static Mapping LoadMapping() => Load<Mapping>(MappingBase64, "mapping");
    private static Target LoadTarget() => Load<Target>(TargetBase64, "target");
    private static T Load<T>(string encoded, string description) where T : class
    {
        string json = Encoding.UTF8.GetString(Convert.FromBase64String(encoded));
        T value = JsonUtility.FromJson<T>(json);
        if (value == null) throw new InvalidOperationException("Invalid CutSceneAI " + description + ".");
        return value;
    }
    private static string ProjectRoot => Directory.GetParent(Application.dataPath).FullName;
    private static string EvidenceRoot => Path.Combine(ProjectRoot, "CutSceneAIEvidence", "Unity");
    private static int ProcessId => System.Diagnostics.Process.GetCurrentProcess().Id;
    private static string AbsoluteAssetPath(string path) => Path.Combine(ProjectRoot, path.Replace('/', Path.DirectorySeparatorChar));
    private static int Frame(double seconds, int fps) => (int)Math.Round(seconds * fps, MidpointRounding.AwayFromZero);
    private static Vector3 Vector(VectorValue value) => new Vector3(value.x, value.y, value.z);
    private static Quaternion QuaternionValueOf(QuaternionValue value) => new Quaternion(value.x, value.y, value.z, value.w);

    private static void ApplyActorTransform(GameObject instance, ActorPlan actor)
    {
        instance.transform.SetPositionAndRotation(
            Vector(actor.transform.position_m), QuaternionValueOf(actor.transform.rotation));
        instance.transform.localScale = Vector(actor.transform.scale);
    }

    private static string Sha256(byte[] data)
    {
        using (SHA256 sha = SHA256.Create())
            return string.Concat(sha.ComputeHash(data).Select(value => value.ToString("x2")));
    }
    private static string Sha256File(string path) => Sha256(File.ReadAllBytes(path));
    private static void EnsureFolder(string assetPath)
    {
        string directory = Path.GetDirectoryName(assetPath).Replace('\\', '/');
        string[] parts = directory.Split('/');
        string current = parts[0];
        for (int index = 1; index < parts.Length; index++)
        {
            string next = current + "/" + parts[index];
            if (!AssetDatabase.IsValidFolder(next)) AssetDatabase.CreateFolder(current, parts[index]);
            current = next;
        }
    }
    private static Transform Find(Transform root, string relativePath)
    {
        if (string.IsNullOrEmpty(relativePath)) return root;
        Transform value = root.Find(relativePath);
        if (value == null) throw new InvalidOperationException("Missing target object path: " + relativePath);
        return value;
    }
    private static ActorTarget ActorTargetFor(Target target, string bindingId)
    {
        ActorTarget value = target.actors.SingleOrDefault(item => item.actor_binding_id == bindingId);
        if (value == null) throw new InvalidOperationException("Missing native actor target: " + bindingId);
        return value;
    }
    private static GameObject LoadPrefab(ActorTarget target)
    {
        GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(target.prefab_path);
        if (prefab == null) throw new InvalidOperationException("Missing target prefab: " + target.prefab_path);
        return prefab;
    }
    private static Animator AnimatorFor(GameObject root, ActorTarget target)
    {
        Animator animator = Find(root.transform, target.animator_path).GetComponent<Animator>();
        if (animator == null || animator.avatar == null || !animator.avatar.isValid || !animator.avatar.isHuman)
            throw new InvalidOperationException("Target requires one valid Humanoid Animator: " + target.actor_binding_id);
        return animator;
    }
    private static SkinnedMeshRenderer FaceFor(GameObject root, ActorTarget target)
    {
        SkinnedMeshRenderer renderer = Find(root.transform, target.facial_renderer_path).GetComponent<SkinnedMeshRenderer>();
        if (renderer == null || renderer.sharedMesh == null)
            throw new InvalidOperationException("Target facial renderer is missing: " + target.actor_binding_id);
        return renderer;
    }

    private static void Preflight(Plan plan, Mapping mapping, Target target)
    {
        if (!Application.unityVersion.StartsWith("6000.0", StringComparison.Ordinal))
            throw new InvalidOperationException("Unity 6000.0 is required, got " + Application.unityVersion + ".");
        UnityEditor.PackageManager.PackageInfo timelinePackage =
            UnityEditor.PackageManager.PackageInfo.FindForAssembly(typeof(TimelineAsset).Assembly);
        if (timelinePackage == null || timelinePackage.version != "1.8.12")
            throw new InvalidOperationException("com.unity.timeline 1.8.12 is required.");
        if (plan.project_id != mapping.project_id || target.project_id != mapping.project_id || plan.fps != mapping.fps)
            throw new InvalidOperationException("Plan, mapping, and native target identity diverged.");
        string[] generatedAssets = mapping.body_tracks.Select(item => item.target_animation_path)
            .Concat(mapping.facial_tracks.Select(item => item.target_animation_path))
            .Concat(mapping.camera_tracks.Select(item => item.target_animation_path))
            .Concat(new[] { target.timeline_asset_path, target.scene_asset_path }).ToArray();
        if (generatedAssets.Distinct().Count() != generatedAssets.Length)
            throw new InvalidOperationException("Native target contains duplicate generated asset paths.");
        foreach (string path in generatedAssets)
            if (AssetDatabase.LoadMainAssetAtPath(path) != null || File.Exists(AbsoluteAssetPath(path)))
                throw new InvalidOperationException("Refusing to replace existing generated asset: " + path);

        string[] requiredShapes = mapping.facial_tracks.SelectMany(item => item.curve_bindings)
            .Select(item => item.target_blendshape_name).Distinct().OrderBy(item => item).ToArray();
        foreach (ActorTarget actorTarget in target.actors)
        {
            GameObject prefab = LoadPrefab(actorTarget);
            Animator animator = AnimatorFor(prefab, actorTarget);
            foreach (BodyTrack body in mapping.body_tracks.Where(item => item.actor_binding_id == actorTarget.actor_binding_id))
                foreach (JointBinding binding in body.joint_bindings)
                    if (animator.GetBoneTransform((HumanBodyBones)Enum.Parse(typeof(HumanBodyBones), binding.target_human_bone)) == null)
                        throw new InvalidOperationException("Humanoid bone is not mapped: " + binding.target_human_bone);
            SkinnedMeshRenderer face = FaceFor(prefab, actorTarget);
            if (!face.transform.IsChildOf(animator.transform))
                throw new InvalidOperationException("Target facial renderer must be below the Humanoid Animator: " + actorTarget.actor_binding_id);
            string[] actualShapes = Enumerable.Range(0, face.sharedMesh.blendShapeCount)
                .Select(index => face.sharedMesh.GetBlendShapeName(index)).ToArray();
            string[] missing = requiredShapes.Except(actualShapes).ToArray();
            if (missing.Length != 0) throw new InvalidOperationException("Target is missing ARKit-52 blendshapes: " + string.Join(", ", missing));
        }
        foreach (AudioTrack audio in mapping.audio_tracks)
        {
            string path = AbsoluteAssetPath(audio.target_audio_path);
            if (!File.Exists(path) || Sha256File(path) != audio.source_artifact.sha256)
                throw new InvalidOperationException("Bundled WAV is missing or changed: " + audio.target_audio_path);
            if (AssetDatabase.LoadAssetAtPath<AudioClip>(audio.target_audio_path) == null)
                throw new InvalidOperationException("Bundled WAV did not import as AudioClip: " + audio.target_audio_path);
        }
    }

    private static AnimationCurve Curve(IEnumerable<Keyframe> keys) => new AnimationCurve(keys.ToArray());
    private static void SetCurve(AnimationClip clip, string path, Type type, string property, IEnumerable<Keyframe> keys)
        => AnimationUtility.SetEditorCurve(clip, EditorCurveBinding.FloatCurve(path, type, property), Curve(keys));
    private static IEnumerable<Keyframe> Keys(int startFrame, int fps, IEnumerable<Tuple<int, float>> values)
        => values.Select(item => new Keyframe((float)(item.Item1 - startFrame) / fps, item.Item2));

    private static AnimationClip CreateBodyClip(BodyTrack track, GameObject prefab, ActorTarget target, int fps)
    {
        Animator animator = AnimatorFor(prefab, target);
        AnimationClip clip = new AnimationClip { name = Path.GetFileNameWithoutExtension(track.target_animation_path), frameRate = fps };
        for (int jointIndex = 0; jointIndex < track.joint_bindings.Length; jointIndex++)
        {
            HumanBodyBones bone = (HumanBodyBones)Enum.Parse(typeof(HumanBodyBones), track.joint_bindings[jointIndex].target_human_bone);
            Transform transform = animator.GetBoneTransform(bone);
            string path = AnimationUtility.CalculateTransformPath(transform, animator.transform);
            Quaternion reference = transform.localRotation;
            Quaternion[] rotations = track.keyframes.Select(frame => reference * QuaternionValueOf(frame.joint_rotations[jointIndex])).ToArray();
            SetCurve(clip, path, typeof(Transform), "m_LocalRotation.x", Keys(track.start_frame, fps, track.keyframes.Select((frame, index) => Tuple.Create(frame.timeline_frame, rotations[index].x))));
            SetCurve(clip, path, typeof(Transform), "m_LocalRotation.y", Keys(track.start_frame, fps, track.keyframes.Select((frame, index) => Tuple.Create(frame.timeline_frame, rotations[index].y))));
            SetCurve(clip, path, typeof(Transform), "m_LocalRotation.z", Keys(track.start_frame, fps, track.keyframes.Select((frame, index) => Tuple.Create(frame.timeline_frame, rotations[index].z))));
            SetCurve(clip, path, typeof(Transform), "m_LocalRotation.w", Keys(track.start_frame, fps, track.keyframes.Select((frame, index) => Tuple.Create(frame.timeline_frame, rotations[index].w))));
            if (jointIndex == 0)
            {
                Vector3 referencePosition = transform.localPosition;
                SetCurve(clip, path, typeof(Transform), "m_LocalPosition.x", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, referencePosition.x + frame.root_position_m.x))));
                SetCurve(clip, path, typeof(Transform), "m_LocalPosition.y", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, referencePosition.y + frame.root_position_m.y))));
                SetCurve(clip, path, typeof(Transform), "m_LocalPosition.z", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, referencePosition.z + frame.root_position_m.z))));
            }
        }
        clip.EnsureQuaternionContinuity();
        EnsureFolder(track.target_animation_path);
        AssetDatabase.CreateAsset(clip, track.target_animation_path);
        return clip;
    }

    private static AnimationClip CreateFaceClip(FaceTrack track, GameObject prefab, ActorTarget target, int fps)
    {
        Animator animator = AnimatorFor(prefab, target);
        SkinnedMeshRenderer face = FaceFor(prefab, target);
        string path = AnimationUtility.CalculateTransformPath(face.transform, animator.transform);
        AnimationClip clip = new AnimationClip { name = Path.GetFileNameWithoutExtension(track.target_animation_path), frameRate = fps };
        for (int curveIndex = 0; curveIndex < track.curve_bindings.Length; curveIndex++)
        {
            string property = "blendShape." + track.curve_bindings[curveIndex].target_blendshape_name;
            SetCurve(clip, path, typeof(SkinnedMeshRenderer), property,
                Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.weights[curveIndex] * 100.0f))));
        }
        EnsureFolder(track.target_animation_path);
        AssetDatabase.CreateAsset(clip, track.target_animation_path);
        return clip;
    }

    private static AnimationClip CreateCameraClip(CameraTrack track, int fps)
    {
        AnimationClip clip = new AnimationClip { name = Path.GetFileNameWithoutExtension(track.target_animation_path), frameRate = fps };
        SetCurve(clip, "", typeof(Transform), "m_LocalPosition.x", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.position_m.x))));
        SetCurve(clip, "", typeof(Transform), "m_LocalPosition.y", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.position_m.y))));
        SetCurve(clip, "", typeof(Transform), "m_LocalPosition.z", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.position_m.z))));
        SetCurve(clip, "", typeof(Transform), "m_LocalRotation.x", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.rotation.x))));
        SetCurve(clip, "", typeof(Transform), "m_LocalRotation.y", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.rotation.y))));
        SetCurve(clip, "", typeof(Transform), "m_LocalRotation.z", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.rotation.z))));
        SetCurve(clip, "", typeof(Transform), "m_LocalRotation.w", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.rotation.w))));
        SetCurve(clip, "", typeof(Camera), "m_FocalLength", Keys(track.start_frame, fps, track.keyframes.Select(frame => Tuple.Create(frame.timeline_frame, frame.focal_length_mm))));
        clip.EnsureQuaternionContinuity();
        EnsureFolder(track.target_animation_path);
        AssetDatabase.CreateAsset(clip, track.target_animation_path);
        return clip;
    }

    private static TimelineClip AddAnimationClip(AnimationTrack track, string name, AnimationClip animation, int start, int end, int fps)
    {
        TimelineClip clip = track.CreateClip<AnimationPlayableAsset>();
        ((AnimationPlayableAsset)clip.asset).clip = animation;
        clip.start = (double)start / fps;
        clip.duration = (double)(end - start) / fps;
        clip.displayName = name;
        return clip;
    }

    public static void Import()
    {
        Plan plan = LoadPlan(); Mapping mapping = LoadMapping(); Target target = LoadTarget();
        Preflight(plan, mapping, target);
        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        GameObject root = new GameObject("CutSceneAI_" + mapping.source_scene_id);
        PlayableDirector director = root.AddComponent<PlayableDirector>();
        TimelineAsset timeline = ScriptableObject.CreateInstance<TimelineAsset>();
        timeline.name = Path.GetFileNameWithoutExtension(target.timeline_asset_path);
        timeline.editorSettings.frameRate = mapping.fps;
        timeline.durationMode = TimelineAsset.DurationMode.FixedLength;
        timeline.fixedDuration = (double)mapping.duration_frames / mapping.fps;
        EnsureFolder(target.timeline_asset_path);
        AssetDatabase.CreateAsset(timeline, target.timeline_asset_path);
        director.playableAsset = timeline;

        Dictionary<string, GameObject> actors = new Dictionary<string, GameObject>();
        Dictionary<string, AnimationTrack> animationRoots = new Dictionary<string, AnimationTrack>();
        foreach (ActorTarget actorTarget in target.actors)
        {
            GameObject instance = (GameObject)PrefabUtility.InstantiatePrefab(LoadPrefab(actorTarget), scene);
            instance.name = ActorPrefix + actorTarget.actor_binding_id;
            ActorPlan actorPlan = plan.sequences.Single().actors.Single(
                item => item.binding_id == actorTarget.actor_binding_id);
            ApplyActorTransform(instance, actorPlan);
            actors.Add(actorTarget.actor_binding_id, instance);
            AnimationTrack rootTrack = timeline.CreateTrack<AnimationTrack>(null, ActorPrefix + "ANIMATION|" + actorTarget.actor_binding_id);
            director.SetGenericBinding(rootTrack, AnimatorFor(instance, actorTarget));
            animationRoots.Add(actorTarget.actor_binding_id, rootTrack);
        }
        foreach (BodyTrack body in mapping.body_tracks)
        {
            ActorTarget actorTarget = ActorTargetFor(target, body.actor_binding_id);
            AnimationClip animation = CreateBodyClip(body, LoadPrefab(actorTarget), actorTarget, mapping.fps);
            AnimationTrack track = timeline.CreateTrack<AnimationTrack>(animationRoots[body.actor_binding_id], BodyPrefix + body.actor_binding_id + "|" + body.semantic_id);
            AddAnimationClip(track, track.name, animation, body.start_frame, body.end_frame, mapping.fps);
        }
        foreach (FaceTrack face in mapping.facial_tracks)
        {
            ActorTarget actorTarget = ActorTargetFor(target, face.actor_binding_id);
            AnimationClip animation = CreateFaceClip(face, LoadPrefab(actorTarget), actorTarget, mapping.fps);
            AnimationTrack track = timeline.CreateTrack<AnimationTrack>(animationRoots[face.actor_binding_id], FacePrefix + face.actor_binding_id + "|" + face.semantic_id);
            AddAnimationClip(track, track.name, animation, face.start_frame, face.end_frame, mapping.fps);
        }
        foreach (AudioTrack audio in mapping.audio_tracks)
        {
            AudioSource source = actors[audio.actor_binding_id].GetComponent<AudioSource>() ?? actors[audio.actor_binding_id].AddComponent<AudioSource>();
            source.playOnAwake = false;
            AudioTrack track = timeline.CreateTrack<AudioTrack>(null, AudioPrefix + audio.actor_binding_id + "|" + audio.dialogue_cue_id);
            TimelineClip clip = track.CreateClip<AudioPlayableAsset>();
            AudioPlayableAsset playable = (AudioPlayableAsset)clip.asset;
            playable.clip = AssetDatabase.LoadAssetAtPath<AudioClip>(audio.target_audio_path); playable.loop = false;
            clip.start = (double)audio.start_frame / mapping.fps; clip.duration = (double)(audio.end_frame - audio.start_frame) / mapping.fps;
            director.SetGenericBinding(track, source);
        }
        foreach (CameraTrack cameraTrack in mapping.camera_tracks)
        {
            GameObject cameraObject = new GameObject(CameraPrefix + cameraTrack.semantic_id);
            Camera camera = cameraObject.AddComponent<Camera>(); camera.usePhysicalProperties = true;
            camera.sensorSize = new Vector2(cameraTrack.sensor_width_mm, cameraTrack.sensor_height_mm);
            Animator animator = cameraObject.AddComponent<Animator>();
            AnimationClip animation = CreateCameraClip(cameraTrack, mapping.fps);
            AnimationTrack cameraMotion = timeline.CreateTrack<AnimationTrack>(null, CameraMotionPrefix + cameraTrack.semantic_id);
            TimelineClip motion = AddAnimationClip(cameraMotion, cameraMotion.name, animation, cameraTrack.start_frame, cameraTrack.end_frame, mapping.fps);
            director.SetGenericBinding(motion.parentTrack, animator);
            ActivationTrack activation = timeline.CreateTrack<ActivationTrack>(null, CameraPrefix + cameraTrack.semantic_id);
            activation.postPlaybackState = ActivationTrack.PostPlaybackState.Inactive;
            TimelineClip activeClip = activation.CreateDefaultClip();
            activeClip.start = (double)cameraTrack.start_frame / mapping.fps;
            activeClip.duration = (double)(cameraTrack.end_frame - cameraTrack.start_frame) / mapping.fps;
            director.SetGenericBinding(activation, cameraObject);
            cameraObject.SetActive(false);
        }
        EditorUtility.SetDirty(timeline); AssetDatabase.SaveAssets();
        EnsureFolder(target.scene_asset_path); EditorSceneManager.SaveScene(scene, target.scene_asset_path);
        Directory.CreateDirectory(EvidenceRoot);
        Lifecycle receipt = new Lifecycle { lifecycle_version = "0.1.0", import_process_id = ProcessId,
            import_completed = true, saved = true, restarted = false, readback_completed = false,
            render_completed = false, errors = Array.Empty<string>() };
        File.WriteAllText(Path.Combine(EvidenceRoot, "lifecycle.json"), JsonUtility.ToJson(receipt, true), new UTF8Encoding(false));
        Debug.Log("CutSceneAI native Unity import saved successfully.");
    }

    private static RealizedSection Section(string semanticId, string actorId, string assetRef, TimelineClip clip, int fps)
        => new RealizedSection { semantic_id = semanticId, actor_binding_id = actorId, asset_ref = assetRef,
            start_frame = Frame(clip.start, fps), end_frame = Frame(clip.end, fps), placeholder = string.IsNullOrEmpty(assetRef) };
    private static string[] Parts(string name, string prefix)
    {
        if (!name.StartsWith(prefix, StringComparison.Ordinal)) return null;
        string[] parts = name.Substring(prefix.Length).Split('|');
        return parts.Length == 2 ? parts : null;
    }
    private static IEnumerable<TrackAsset> Descendants(TrackAsset track)
    {
        yield return track;
        foreach (TrackAsset child in track.GetChildTracks())
            foreach (TrackAsset descendant in Descendants(child)) yield return descendant;
    }
    private static IEnumerable<TrackAsset> AllTracks(TimelineAsset timeline)
        => timeline.GetRootTracks().SelectMany(Descendants);

    private static EngineReadback Readback(Plan plan, Mapping mapping, Target target, TimelineAsset timeline)
    {
        List<RealizedSection> body = new List<RealizedSection>(); List<RealizedSection> face = new List<RealizedSection>();
        List<RealizedSection> cameras = new List<RealizedSection>(); List<RealizedSection> audio = new List<RealizedSection>();
        foreach (TrackAsset track in AllTracks(timeline))
        {
            string[] parts = Parts(track.name, BodyPrefix);
            if (parts != null && track is AnimationTrack)
                foreach (TimelineClip clip in track.GetClips()) body.Add(Section(parts[1], parts[0], AssetDatabase.GetAssetPath(((AnimationPlayableAsset)clip.asset).clip), clip, mapping.fps));
            parts = Parts(track.name, FacePrefix);
            if (parts != null && track is AnimationTrack)
                foreach (TimelineClip clip in track.GetClips()) face.Add(Section(parts[1], parts[0], AssetDatabase.GetAssetPath(((AnimationPlayableAsset)clip.asset).clip), clip, mapping.fps));
            parts = Parts(track.name, AudioPrefix);
            if (parts != null && track is AudioTrack)
                foreach (TimelineClip clip in track.GetClips()) audio.Add(Section(parts[1], parts[0], AssetDatabase.GetAssetPath(((AudioPlayableAsset)clip.asset).clip), clip, mapping.fps));
            if (track.name.StartsWith(CameraPrefix, StringComparison.Ordinal) && track is ActivationTrack)
            {
                string semanticId = track.name.Substring(CameraPrefix.Length);
                CameraTrack camera = mapping.camera_tracks.Single(item => item.semantic_id == semanticId);
                foreach (TimelineClip clip in track.GetClips()) cameras.Add(Section(semanticId, null, camera.target_animation_path, clip, mapping.fps));
            }
        }
        if (body.Count != mapping.body_tracks.Length || face.Count != mapping.facial_tracks.Length || cameras.Count != mapping.camera_tracks.Length || audio.Count != mapping.audio_tracks.Length)
            throw new InvalidOperationException("Saved Timeline does not contain every generated modality section.");
        return new EngineReadback { readback_version = "0.1.0", engine = "unity", engine_version = Application.unityVersion,
            adapter_version = plan.adapter_version, timeline_asset = target.timeline_asset_path, semantics = plan.semantics,
            evidence = new ReadbackEvidence { animation_sections = body.OrderBy(item => item.semantic_id).ToArray(), facial_sections = face.OrderBy(item => item.semantic_id).ToArray(),
                camera_sections = cameras.OrderBy(item => item.semantic_id).ToArray(), audio_sections = audio.OrderBy(item => item.semantic_id).ToArray() },
            warnings = Array.Empty<string>() };
    }

    private static RenderManifest Render(Mapping mapping, Target target, PlayableDirector director)
    {
        string output = Path.Combine(ProjectRoot, target.render.output_directory.Replace('/', Path.DirectorySeparatorChar));
        if (Directory.Exists(output) && Directory.EnumerateFileSystemEntries(output).Any())
            throw new InvalidOperationException("Refusing to replace existing render output: " + output);
        Directory.CreateDirectory(output);
        List<RenderedFrame> frames = new List<RenderedFrame>();
        RenderTexture texture = new RenderTexture(target.render.width, target.render.height, 24, RenderTextureFormat.ARGB32);
        Texture2D pixels = new Texture2D(target.render.width, target.render.height, TextureFormat.RGB24, false);
        try
        {
            for (int frame = 0; frame < mapping.duration_frames; frame++)
            {
                director.time = (double)frame / mapping.fps; director.Evaluate();
                Camera[] active = UnityEngine.Object.FindObjectsByType<Camera>(FindObjectsSortMode.None)
                    .Where(item => item.gameObject.activeInHierarchy && item.enabled).ToArray();
                if (active.Length != 1) throw new InvalidOperationException("Expected exactly one active generated camera at frame " + frame + ".");
                Camera camera = active[0]; camera.targetTexture = texture; RenderTexture.active = texture; camera.Render();
                pixels.ReadPixels(new Rect(0, 0, target.render.width, target.render.height), 0, 0); pixels.Apply();
                byte[] png = pixels.EncodeToPNG(); string name = frame.ToString("D6") + ".png";
                File.WriteAllBytes(Path.Combine(output, name), png);
                frames.Add(new RenderedFrame { frame = frame, relative_path = name, sha256 = Sha256(png) });
                camera.targetTexture = null;
            }
        }
        finally { RenderTexture.active = null; UnityEngine.Object.DestroyImmediate(pixels); texture.Release(); UnityEngine.Object.DestroyImmediate(texture); }
        return new RenderManifest { manifest_version = "0.1.0", engine = "unity", source_bundle_sha256 = mapping.source_bundle_sha256,
            expected_frame_count = mapping.duration_frames, rendered_frame_count = frames.Count, frames = frames.ToArray() };
    }

    public static void ReadbackAndRender()
    {
        Plan plan = LoadPlan(); Mapping mapping = LoadMapping(); Target target = LoadTarget();
        string lifecyclePath = Path.Combine(EvidenceRoot, "lifecycle.json");
        if (!File.Exists(lifecyclePath)) throw new InvalidOperationException("Native import receipt is missing.");
        Lifecycle lifecycle = JsonUtility.FromJson<Lifecycle>(File.ReadAllText(lifecyclePath));
        if (!lifecycle.import_completed || !lifecycle.saved || lifecycle.import_process_id == ProcessId)
            throw new InvalidOperationException("Readback must run after a separate saved editor process.");
        EditorSceneManager.OpenScene(target.scene_asset_path, OpenSceneMode.Single);
        TimelineAsset timeline = AssetDatabase.LoadAssetAtPath<TimelineAsset>(target.timeline_asset_path);
        if (timeline == null) throw new InvalidOperationException("Saved Timeline is missing after restart.");
        PlayableDirector director = UnityEngine.Object.FindObjectsByType<PlayableDirector>(FindObjectsSortMode.None).Single(item => item.playableAsset == timeline);
        EngineReadback readback = Readback(plan, mapping, target, timeline);
        Directory.CreateDirectory(EvidenceRoot);
        File.WriteAllText(Path.Combine(EvidenceRoot, "readback.json"), JsonUtility.ToJson(readback, true), new UTF8Encoding(false));
        RenderManifest manifest = Render(mapping, target, director);
        File.WriteAllText(Path.Combine(EvidenceRoot, "render-manifest.json"), JsonUtility.ToJson(manifest, true), new UTF8Encoding(false));
        lifecycle.readback_process_id = ProcessId; lifecycle.restarted = true; lifecycle.readback_completed = true;
        lifecycle.render_completed = manifest.rendered_frame_count == manifest.expected_frame_count;
        File.WriteAllText(lifecyclePath, JsonUtility.ToJson(lifecycle, true), new UTF8Encoding(false));
        Debug.Log("CutSceneAI native Unity restart/readback/render completed successfully.");
    }
}
"""


def render_unity_native_performance_script(
    package: UnityNativePerformancePackage,
) -> str:
    """Render the deterministic Unity editor realization/readback/render script."""

    return (
        _UNITY_NATIVE_TEMPLATE.replace("__PLAN_BASE64__", _encoded_json(package.plan))
        .replace("__MAPPING_BASE64__", _encoded_json(package.mapping))
        .replace("__TARGET_BASE64__", _encoded_json(package.target))
    )


_UNITY_RUNNER_TEMPLATE = r"""[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$UnityEditor,
    [Parameter(Mandatory = $true)][string]$ProjectPath,
    [string]$Python = "python"
)
$ErrorActionPreference = "Stop"
$packageRoot = Split-Path -Parent $PSScriptRoot
$projectRoot = (Resolve-Path $ProjectPath).Path
$bundlePath = Join-Path $packageRoot "performance.bundle.zip"
$actualBundleHash = (Get-FileHash -Algorithm SHA256 $bundlePath).Hash.ToLowerInvariant()
if ($actualBundleHash -ne "__BUNDLE_SHA256__") { throw "Performance bundle checksum mismatch." }

function Copy-CutSceneAIFile([string]$Source, [string]$Destination) {
    if (Test-Path $Destination) { throw "Refusing to replace existing project file: $Destination" }
    $directory = Split-Path -Parent $Destination
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
    Copy-Item -LiteralPath $Source -Destination $Destination
}

$editorSource = Join-Path $PSScriptRoot "CutSceneAIGeneratedPerformance.cs"
$editorTarget = Join-Path $projectRoot "Assets\Editor\CutSceneAIGeneratedPerformance.cs"
Copy-CutSceneAIFile $editorSource $editorTarget
$audioTargets = ConvertFrom-Json @'
__AUDIO_TARGETS_JSON__
'@
foreach ($audio in $audioTargets) {
    $source = Join-Path $packageRoot $audio.source
    $destination = Join-Path $projectRoot $audio.destination
    Copy-CutSceneAIFile $source $destination
    $hash = (Get-FileHash -Algorithm SHA256 $destination).Hash.ToLowerInvariant()
    if ($hash -ne $audio.sha256) { throw "Copied WAV checksum mismatch: $destination" }
}

$evidenceRoot = Join-Path $projectRoot "CutSceneAIEvidence\Unity"
New-Item -ItemType Directory -Force -Path $evidenceRoot | Out-Null
$importLog = Join-Path $evidenceRoot "import.log"
& $UnityEditor -batchmode -quit -projectPath $projectRoot -logFile $importLog -executeMethod CutSceneAIGeneratedPerformance.Import
if ($LASTEXITCODE -ne 0) { throw "Unity native import failed with exit code $LASTEXITCODE. See $importLog" }
$readbackLog = Join-Path $evidenceRoot "readback-render.log"
& $UnityEditor -batchmode -quit -projectPath $projectRoot -logFile $readbackLog -executeMethod CutSceneAIGeneratedPerformance.ReadbackAndRender
if ($LASTEXITCODE -ne 0) { throw "Unity restart/readback/render failed with exit code $LASTEXITCODE. See $readbackLog" }
$combinedLog = Join-Path $evidenceRoot "editor.log"
Get-Content -Raw -Path $importLog, $readbackLog | Set-Content -NoNewline -Encoding UTF8 $combinedLog
& $Python (Join-Path $PSScriptRoot "collect-native-evidence.py") --engine unity --mapping (Join-Path $packageRoot "mapping.json") --lifecycle (Join-Path $evidenceRoot "lifecycle.json") --readback (Join-Path $evidenceRoot "readback.json") --render-manifest (Join-Path $evidenceRoot "render-manifest.json") --editor-log $combinedLog --output (Join-Path $evidenceRoot "engine-run.evidence.json")
if ($LASTEXITCODE -ne 0) { throw "Native evidence collection failed with exit code $LASTEXITCODE." }
Write-Host "CutSceneAI Unity native gate completed: $evidenceRoot"
"""


def _windows_relative(path: str) -> str:
    return path.replace("/", "\\")


def render_unity_native_runner_script(
    package: UnityNativePerformancePackage,
) -> str:
    audio_targets = []
    for track in package.mapping.audio_tracks:
        source = f"Payload/{track.target_audio_path}"
        audio_targets.append(
            {
                "source": _windows_relative(source),
                "destination": _windows_relative(track.target_audio_path),
                "sha256": track.source_artifact.sha256,
            }
        )
    bundle_data = render_performance_bundle(package.bundle)
    return _UNITY_RUNNER_TEMPLATE.replace(
        "__BUNDLE_SHA256__", _sha256(bundle_data)
    ).replace(
        "__AUDIO_TARGETS_JSON__",
        json.dumps(audio_targets, indent=2, sort_keys=True),
    )


def _write_entry(archive: ZipFile, path: str, data: bytes) -> None:
    entry = ZipInfo(path, date_time=_ZIP_TIMESTAMP)
    entry.compress_type = ZIP_DEFLATED
    entry.external_attr = 0o644 << 16
    archive.writestr(entry, data)


def render_unity_native_performance_package(
    package: UnityNativePerformancePackage,
    *,
    evidence_collector_script: str,
) -> bytes:
    """Render a deterministic portable Unity native-realization harness archive."""

    output = BytesIO()
    with ZipFile(output, "w") as archive:
        _write_entry(
            archive,
            "Scripts/CutSceneAIGeneratedPerformance.cs",
            render_unity_native_performance_script(package).encode("utf-8"),
        )
        _write_entry(
            archive,
            "Scripts/run-unity-native.ps1",
            render_unity_native_runner_script(package).encode("utf-8"),
        )
        _write_entry(
            archive,
            "Scripts/collect-native-evidence.py",
            evidence_collector_script.encode("utf-8"),
        )
        _write_entry(
            archive,
            "mapping.json",
            render_unity_performance_mapping(package.mapping).encode("utf-8"),
        )
        _write_entry(
            archive,
            "plan.json",
            render_unity_plan(package.plan).encode("utf-8"),
        )
        _write_entry(
            archive,
            "target.json",
            (
                json.dumps(
                    package.target.model_dump(mode="json"), indent=2, sort_keys=True
                )
                + "\n"
            ).encode("utf-8"),
        )
        _write_entry(
            archive,
            "performance.bundle.zip",
            render_performance_bundle(package.bundle),
        )
        audio_by_path = {
            track.artifact.relative_path: track
            for track in package.bundle.package.audio_tracks
        }
        for mapped in package.mapping.audio_tracks:
            source_track = audio_by_path[mapped.source_artifact.relative_path]
            data = package.bundle.artifact_files[source_track.artifact.relative_path]
            if _sha256(data) != mapped.source_artifact.sha256:
                raise ValueError(
                    "Unity native package WAV changed after bundle verification."
                )
            path = PurePosixPath("Payload") / mapped.target_audio_path
            _write_entry(archive, path.as_posix(), data)
    return output.getvalue()
