from __future__ import annotations

import base64
import json

from .models import UnityExportPlan


_CS_TEMPLATE = r"""// Generated by CutSceneAI Unity Adapter v0.1.0.
// Keep this file under Assets/Editor so the readback command remains available after restart.
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.SceneManagement;
using UnityEngine.Timeline;

[Serializable]
public sealed class CutSceneAISemanticMarker : Marker, INotification
{
    public string semantic_kind;
    public string semantic_id;
    public string actor_binding_id;
    public int end_frame;

    public PropertyName id => new PropertyName(semantic_kind + ":" + semantic_id);
}

public static class CutSceneAIGeneratedTimeline
{
    private const string PlanBase64 = "__PLAN_BASE64__";
    private const string MetadataName = "CSA_TIMELINE_SEMANTICS_V0_1";
    private const string EntityPrefix = "CSA|ENTITY|";
    private const string AnimationTrackPrefix = "CSA|ANIMATION|";
    private const string PerformanceClipPrefix = "CSA|PERFORMANCE|";
    private const string AudioTrackPrefix = "CSA|AUDIO|";
    private const string DialogueClipPrefix = "CSA|DIALOGUE|";
    private const string CameraTrackPrefix = "CSA|CAMERA|";

    [Serializable]
    private sealed class Plan
    {
        public string adapter_version;
        public string project_id;
        public int fps;
        public TimelineSemantics semantics;
        public ScenePlan[] sequences;
        public Warning[] warnings;
    }

    [Serializable]
    private sealed class Warning
    {
        public string code;
        public string source_id;
        public string message;
    }

    [Serializable]
    private sealed class ScenePlan
    {
        public string source_scene_id;
        public string timeline_asset_path;
        public string scene_asset_path;
        public int duration_frames;
        public ActorPlan[] actors;
        public AnimationSection[] animation_sections;
        public AudioSection[] audio_sections;
        public CameraCutPlan[] cameras;
    }

    [Serializable]
    private sealed class ActorPlan
    {
        public string binding_id;
        public string source_entity_id;
        public string display_name;
        public string kind;
        public string prefab_path;
        public bool placeholder;
        public string placeholder_primitive;
        public TransformPlan transform;
    }

    [Serializable]
    private sealed class TransformPlan
    {
        public VectorPlan position_m;
        public QuaternionPlan rotation;
        public VectorPlan scale;
    }

    [Serializable]
    private sealed class VectorPlan
    {
        public float x;
        public float y;
        public float z;
    }

    [Serializable]
    private sealed class QuaternionPlan
    {
        public float x;
        public float y;
        public float z;
        public float w;
    }

    [Serializable]
    private sealed class AnimationSection
    {
        public string cue_id;
        public string actor_binding_id;
        public int start_frame;
        public int end_frame;
        public string asset_path;
        public bool placeholder;
    }

    [Serializable]
    private sealed class AudioSection
    {
        public string cue_id;
        public string actor_binding_id;
        public int start_frame;
        public int end_frame;
        public string asset_path;
    }

    [Serializable]
    private sealed class CameraCutPlan
    {
        public string cut_id;
        public string display_name;
        public int start_frame;
        public int end_frame;
        public float lens_mm;
        public VectorPlan position_m;
        public VectorPlan look_at_m;
    }

    [Serializable]
    private sealed class TimelineSemantics
    {
        public string semantics_version;
        public string cir_schema_version;
        public string cir_fingerprint_sha256;
        public string project_id;
        public int fps;
        public SemanticScene[] scenes;
    }

    [Serializable]
    private sealed class SemanticScene
    {
        public string source_scene_id;
        public int duration_frames;
        public SemanticEntity[] entities;
        public SemanticPerformance[] performance_cues;
        public SemanticDialogue[] dialogue_cues;
        public SemanticCamera[] camera_cuts;
    }

    [Serializable]
    private sealed class SemanticEntity
    {
        public string binding_id;
        public string source_entity_id;
        public string kind;
    }

    [Serializable]
    private sealed class SemanticPerformance
    {
        public string cue_id;
        public string source_beat_id;
        public string actor_binding_id;
        public int start_frame;
        public int end_frame;
        public string motion_intent_sha256;
        public string look_at_binding_id;
    }

    [Serializable]
    private sealed class SemanticDialogue
    {
        public string cue_id;
        public string source_beat_id;
        public string actor_binding_id;
        public int start_frame;
        public int window_end_frame;
        public string text_sha256;
        public string language;
    }

    [Serializable]
    private sealed class SemanticCamera
    {
        public string cut_id;
        public string source_shot_id;
        public string[] source_beat_ids;
        public int start_frame;
        public int end_frame;
        public string purpose;
        public string framing;
        public string angle;
        public string movement;
        public float lens_mm;
        public string[] subject_binding_ids;
        public string[] target_binding_ids;
    }

    [Serializable]
    private sealed class RealizedSection
    {
        public string semantic_id;
        public string actor_binding_id;
        public string asset_ref;
        public int start_frame;
        public int end_frame;
        public bool placeholder;
    }

    [Serializable]
    private sealed class ReadbackEvidence
    {
        public RealizedSection[] animation_sections;
        public RealizedSection[] audio_sections;
    }

    [Serializable]
    private sealed class EngineReadback
    {
        public string readback_version;
        public string engine;
        public string engine_version;
        public string adapter_version;
        public string timeline_asset;
        public TimelineSemantics semantics;
        public ReadbackEvidence evidence;
        public string[] warnings;
    }

    [MenuItem("CutSceneAI/Import Generated Timeline")]
    public static void ImportGeneratedTimeline()
    {
        Plan plan = LoadPlan();
        Preflight(plan);
        foreach (ScenePlan scenePlan in plan.sequences)
        {
            CreateTimeline(plan, scenePlan);
        }
        AssetDatabase.SaveAssets();
        ExportReadbackInternal(plan);
        Debug.Log("CutSceneAI created Unity Timelines and exported a semantic readback.");
    }

    [MenuItem("CutSceneAI/Export Generated Timeline Readback")]
    public static void ExportGeneratedTimelineReadback()
    {
        ExportReadbackInternal(LoadPlan());
    }

    private static Plan LoadPlan()
    {
        string json = Encoding.UTF8.GetString(Convert.FromBase64String(PlanBase64));
        Plan plan = JsonUtility.FromJson<Plan>(json);
        if (plan == null || plan.sequences == null || plan.semantics == null)
        {
            throw new InvalidOperationException("CutSceneAI Unity plan is invalid.");
        }
        return plan;
    }

    private static void Preflight(Plan plan)
    {
        foreach (ScenePlan scene in plan.sequences)
        {
            if (AssetDatabase.LoadAssetAtPath<TimelineAsset>(scene.timeline_asset_path) != null)
            {
                throw new InvalidOperationException(
                    "Refusing to replace existing Timeline asset '" +
                    scene.timeline_asset_path + "'."
                );
            }
            if (AssetDatabase.LoadAssetAtPath<SceneAsset>(scene.scene_asset_path) != null)
            {
                throw new InvalidOperationException(
                    "Refusing to replace existing Scene asset '" + scene.scene_asset_path + "'."
                );
            }
            foreach (ActorPlan actor in scene.actors)
            {
                if (!string.IsNullOrEmpty(actor.prefab_path) &&
                    AssetDatabase.LoadAssetAtPath<GameObject>(actor.prefab_path) == null)
                {
                    throw new InvalidOperationException(
                        "Mapped Unity prefab does not exist: " + actor.prefab_path
                    );
                }
            }
            foreach (AnimationSection animation in scene.animation_sections)
            {
                if (!string.IsNullOrEmpty(animation.asset_path) &&
                    AssetDatabase.LoadAssetAtPath<AnimationClip>(animation.asset_path) == null)
                {
                    throw new InvalidOperationException(
                        "Mapped Unity AnimationClip does not exist: " + animation.asset_path
                    );
                }
            }
            foreach (AudioSection audio in scene.audio_sections)
            {
                if (AssetDatabase.LoadAssetAtPath<AudioClip>(audio.asset_path) == null)
                {
                    throw new InvalidOperationException(
                        "Mapped Unity AudioClip does not exist: " + audio.asset_path
                    );
                }
            }
        }
    }

    private static void EnsureAssetFolder(string assetPath)
    {
        string directory = Path.GetDirectoryName(assetPath).Replace('\\', '/');
        string[] parts = directory.Split('/');
        string current = parts[0];
        for (int index = 1; index < parts.Length; index++)
        {
            string next = current + "/" + parts[index];
            if (!AssetDatabase.IsValidFolder(next))
            {
                AssetDatabase.CreateFolder(current, parts[index]);
            }
            current = next;
        }
    }

    private static Vector3 Vector(VectorPlan value)
    {
        return new Vector3(value.x, value.y, value.z);
    }

    private static Quaternion QuaternionValue(QuaternionPlan value)
    {
        return new Quaternion(value.x, value.y, value.z, value.w);
    }

    private static GameObject AddActor(ActorPlan actor)
    {
        GameObject result;
        if (!string.IsNullOrEmpty(actor.prefab_path))
        {
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(actor.prefab_path);
            result = PrefabUtility.InstantiatePrefab(prefab) as GameObject;
            if (result == null)
            {
                throw new InvalidOperationException("Unable to instantiate " + actor.prefab_path);
            }
        }
        else
        {
            PrimitiveType primitive = actor.placeholder_primitive == "capsule"
                ? PrimitiveType.Capsule
                : PrimitiveType.Cube;
            result = GameObject.CreatePrimitive(primitive);
        }
        result.name = EntityPrefix + actor.binding_id;
        result.transform.position = Vector(actor.transform.position_m);
        result.transform.rotation = QuaternionValue(actor.transform.rotation);
        result.transform.localScale = Vector(actor.transform.scale);
        if (actor.kind == "character" && result.GetComponentInChildren<Animator>() == null)
        {
            result.AddComponent<Animator>();
        }
        return result;
    }

    private static void AddSemanticMarkers(
        TimelineAsset timeline,
        SemanticScene semantics,
        int fps
    )
    {
        timeline.CreateMarkerTrack();
        MarkerTrack markerTrack = timeline.markerTrack;
        markerTrack.name = "CSA|SEMANTICS";
        foreach (SemanticPerformance cue in semantics.performance_cues)
        {
            CutSceneAISemanticMarker marker =
                markerTrack.CreateMarker<CutSceneAISemanticMarker>((double)cue.start_frame / fps);
            marker.semantic_kind = "performance";
            marker.semantic_id = cue.cue_id;
            marker.actor_binding_id = cue.actor_binding_id;
            marker.end_frame = cue.end_frame;
        }
        foreach (SemanticDialogue cue in semantics.dialogue_cues)
        {
            CutSceneAISemanticMarker marker =
                markerTrack.CreateMarker<CutSceneAISemanticMarker>((double)cue.start_frame / fps);
            marker.semantic_kind = "dialogue";
            marker.semantic_id = cue.cue_id;
            marker.actor_binding_id = cue.actor_binding_id;
            marker.end_frame = cue.window_end_frame;
        }
    }

    private static AnimationClip PlaceholderAnimation(
        TimelineAsset timeline,
        string cueId
    )
    {
        AnimationClip clip = new AnimationClip();
        clip.name = "CSA_PLACEHOLDER_" + cueId.Replace(':', '_');
        AssetDatabase.AddObjectToAsset(clip, timeline);
        return clip;
    }

    private static void AddAnimations(
        TimelineAsset timeline,
        PlayableDirector director,
        ScenePlan scene,
        Dictionary<string, GameObject> actors,
        int fps
    )
    {
        foreach (IGrouping<string, AnimationSection> group in
                 scene.animation_sections.GroupBy(item => item.actor_binding_id))
        {
            GameObject actor = actors[group.Key];
            Animator animator = actor.GetComponentInChildren<Animator>();
            if (animator == null)
            {
                throw new InvalidOperationException("Actor has no Animator: " + group.Key);
            }
            AnimationTrack track = timeline.CreateTrack<AnimationTrack>(
                null,
                AnimationTrackPrefix + group.Key
            );
            track.trackOffset = TrackOffset.ApplySceneOffsets;
            director.SetGenericBinding(track, animator);
            foreach (AnimationSection section in group.OrderBy(item => item.start_frame))
            {
                TimelineClip timelineClip = track.CreateClip<AnimationPlayableAsset>();
                AnimationPlayableAsset playable = (AnimationPlayableAsset)timelineClip.asset;
                playable.clip = string.IsNullOrEmpty(section.asset_path)
                    ? PlaceholderAnimation(timeline, section.cue_id)
                    : AssetDatabase.LoadAssetAtPath<AnimationClip>(section.asset_path);
                timelineClip.start = (double)section.start_frame / fps;
                timelineClip.duration = (double)(section.end_frame - section.start_frame) / fps;
                timelineClip.displayName = PerformanceClipPrefix + section.cue_id;
            }
        }
    }

    private static void AddAudio(
        TimelineAsset timeline,
        PlayableDirector director,
        ScenePlan scene,
        Dictionary<string, GameObject> actors,
        int fps
    )
    {
        foreach (IGrouping<string, AudioSection> group in
                 scene.audio_sections.GroupBy(item => item.actor_binding_id))
        {
            GameObject actor = actors[group.Key];
            AudioSource source = actor.GetComponent<AudioSource>();
            if (source == null)
            {
                source = actor.AddComponent<AudioSource>();
            }
            source.playOnAwake = false;
            AudioTrack track = timeline.CreateTrack<AudioTrack>(null, AudioTrackPrefix + group.Key);
            director.SetGenericBinding(track, source);
            foreach (AudioSection section in group.OrderBy(item => item.start_frame))
            {
                TimelineClip timelineClip = track.CreateClip<AudioPlayableAsset>();
                AudioPlayableAsset playable = (AudioPlayableAsset)timelineClip.asset;
                playable.clip = AssetDatabase.LoadAssetAtPath<AudioClip>(section.asset_path);
                playable.loop = false;
                timelineClip.start = (double)section.start_frame / fps;
                timelineClip.duration = (double)(section.end_frame - section.start_frame) / fps;
                timelineClip.displayName = DialogueClipPrefix + section.cue_id;
            }
        }
    }

    private static void AddCameras(
        TimelineAsset timeline,
        PlayableDirector director,
        ScenePlan scene,
        int fps
    )
    {
        foreach (CameraCutPlan cut in scene.cameras)
        {
            GameObject cameraObject = new GameObject(EntityPrefix + cut.cut_id);
            Camera camera = cameraObject.AddComponent<Camera>();
            camera.focalLength = cut.lens_mm;
            cameraObject.transform.position = Vector(cut.position_m);
            Vector3 target = Vector(cut.look_at_m);
            if ((target - cameraObject.transform.position).sqrMagnitude > 0.000001f)
            {
                cameraObject.transform.LookAt(target, Vector3.up);
            }
            cameraObject.SetActive(false);
            ActivationTrack track = timeline.CreateTrack<ActivationTrack>(
                null,
                CameraTrackPrefix + cut.cut_id
            );
            track.postPlaybackState = ActivationTrack.PostPlaybackState.Inactive;
            director.SetGenericBinding(track, cameraObject);
            TimelineClip clip = track.CreateDefaultClip();
            clip.start = (double)cut.start_frame / fps;
            clip.duration = (double)(cut.end_frame - cut.start_frame) / fps;
            clip.displayName = CameraTrackPrefix + cut.cut_id;
        }
    }

    private static SemanticScene FindSemanticScene(
        TimelineSemantics semantics,
        string sourceSceneId
    )
    {
        SemanticScene result = semantics.scenes.FirstOrDefault(
            item => item.source_scene_id == sourceSceneId
        );
        if (result == null)
        {
            throw new InvalidOperationException(
                "Semantic timeline is missing scene '" + sourceSceneId + "'."
            );
        }
        return result;
    }

    private static void CreateTimeline(Plan plan, ScenePlan scenePlan)
    {
        EnsureAssetFolder(scenePlan.timeline_asset_path);
        EnsureAssetFolder(scenePlan.scene_asset_path);
        Scene scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        GameObject root = new GameObject("CutSceneAI_" + scenePlan.source_scene_id);
        PlayableDirector director = root.AddComponent<PlayableDirector>();
        TimelineAsset timeline = ScriptableObject.CreateInstance<TimelineAsset>();
        timeline.name = Path.GetFileNameWithoutExtension(scenePlan.timeline_asset_path);
        timeline.editorSettings.frameRate = plan.fps;
        timeline.durationMode = TimelineAsset.DurationMode.FixedLength;
        timeline.fixedDuration = (double)scenePlan.duration_frames / plan.fps;
        AssetDatabase.CreateAsset(timeline, scenePlan.timeline_asset_path);

        TextAsset metadata = new TextAsset(JsonUtility.ToJson(plan.semantics));
        metadata.name = MetadataName;
        AssetDatabase.AddObjectToAsset(metadata, timeline);
        director.playableAsset = timeline;

        Dictionary<string, GameObject> actors = new Dictionary<string, GameObject>();
        foreach (ActorPlan actor in scenePlan.actors)
        {
            actors.Add(actor.binding_id, AddActor(actor));
        }
        SemanticScene semantics = FindSemanticScene(plan.semantics, scenePlan.source_scene_id);
        AddSemanticMarkers(timeline, semantics, plan.fps);
        AddAnimations(timeline, director, scenePlan, actors, plan.fps);
        AddAudio(timeline, director, scenePlan, actors, plan.fps);
        AddCameras(timeline, director, scenePlan, plan.fps);
        EditorUtility.SetDirty(timeline);
        EditorSceneManager.SaveScene(scene, scenePlan.scene_asset_path);
    }

    private static int Frame(double seconds, int fps)
    {
        return (int)Math.Round(seconds * fps, MidpointRounding.AwayFromZero);
    }

    private static int TimelineFps(TimelineAsset timeline)
    {
        double value = timeline.editorSettings.frameRate;
        int rounded = (int)Math.Round(value, MidpointRounding.AwayFromZero);
        if (rounded <= 0 || Math.Abs(value - rounded) > 0.000001)
        {
            throw new InvalidOperationException(
                "CutSceneAI parity requires a whole-number Timeline frame rate."
            );
        }
        return rounded;
    }

    private static string StripPrefix(string value, string prefix)
    {
        return value.StartsWith(prefix, StringComparison.Ordinal)
            ? value.Substring(prefix.Length)
            : null;
    }

    private static TimelineSemantics LoadAttachedSemantics(TimelineAsset timeline)
    {
        string path = AssetDatabase.GetAssetPath(timeline);
        TextAsset metadata = AssetDatabase.LoadAllAssetsAtPath(path)
            .OfType<TextAsset>()
            .SingleOrDefault(item => item.name == MetadataName);
        if (metadata == null)
        {
            throw new InvalidOperationException(
                "Timeline has no CutSceneAI semantic metadata: " + path
            );
        }
        TimelineSemantics semantics = JsonUtility.FromJson<TimelineSemantics>(metadata.text);
        if (semantics == null)
        {
            throw new InvalidOperationException("Timeline semantic metadata is invalid: " + path);
        }
        return semantics;
    }

    private static void ReadSemanticMarkers(
        TimelineAsset timeline,
        SemanticScene scene,
        int fps
    )
    {
        HashSet<string> performanceIds = new HashSet<string>();
        HashSet<string> dialogueIds = new HashSet<string>();
        if (timeline.markerTrack != null)
        {
            foreach (CutSceneAISemanticMarker marker in
                     timeline.markerTrack.GetMarkers().OfType<CutSceneAISemanticMarker>())
            {
                if (marker.semantic_kind == "performance")
                {
                    SemanticPerformance cue = scene.performance_cues.FirstOrDefault(
                        item => item.cue_id == marker.semantic_id
                    );
                    if (cue == null)
                    {
                        throw new InvalidOperationException(
                            "Unknown CutSceneAI performance marker: " + marker.semantic_id
                        );
                    }
                    if (!performanceIds.Add(cue.cue_id))
                    {
                        throw new InvalidOperationException(
                            "Duplicate CutSceneAI performance marker: " + marker.semantic_id
                        );
                    }
                    cue.actor_binding_id = marker.actor_binding_id;
                    cue.start_frame = Frame(marker.time, fps);
                    cue.end_frame = marker.end_frame;
                }
                else if (marker.semantic_kind == "dialogue")
                {
                    SemanticDialogue cue = scene.dialogue_cues.FirstOrDefault(
                        item => item.cue_id == marker.semantic_id
                    );
                    if (cue == null)
                    {
                        throw new InvalidOperationException(
                            "Unknown CutSceneAI dialogue marker: " + marker.semantic_id
                        );
                    }
                    if (!dialogueIds.Add(cue.cue_id))
                    {
                        throw new InvalidOperationException(
                            "Duplicate CutSceneAI dialogue marker: " + marker.semantic_id
                        );
                    }
                    cue.actor_binding_id = marker.actor_binding_id;
                    cue.start_frame = Frame(marker.time, fps);
                    cue.window_end_frame = marker.end_frame;
                }
                else
                {
                    throw new InvalidOperationException(
                        "Unknown CutSceneAI semantic marker kind: " + marker.semantic_kind
                    );
                }
            }
        }
        scene.performance_cues = scene.performance_cues
            .Where(item => performanceIds.Contains(item.cue_id))
            .ToArray();
        scene.dialogue_cues = scene.dialogue_cues
            .Where(item => dialogueIds.Contains(item.cue_id))
            .ToArray();
    }

    private static void ReadEntities(SemanticScene scene)
    {
        scene.entities = scene.entities
            .Where(item => GameObject.Find(EntityPrefix + item.binding_id) != null)
            .ToArray();
    }

    private static void ReadTracks(
        TimelineAsset timeline,
        PlayableDirector director,
        SemanticScene scene,
        int fps,
        List<RealizedSection> animations,
        List<RealizedSection> audio
    )
    {
        HashSet<string> cameraIds = new HashSet<string>();
        foreach (TrackAsset track in timeline.GetOutputTracks())
        {
            string actorBinding = StripPrefix(track.name, AnimationTrackPrefix);
            if (actorBinding != null && track is AnimationTrack)
            {
                foreach (TimelineClip clip in track.GetClips())
                {
                    string cueId = StripPrefix(clip.displayName, PerformanceClipPrefix);
                    if (cueId == null)
                    {
                        continue;
                    }
                    AnimationPlayableAsset playable = clip.asset as AnimationPlayableAsset;
                    animations.Add(new RealizedSection {
                        semantic_id = cueId,
                        actor_binding_id = actorBinding,
                        asset_ref = playable != null && playable.clip != null
                            ? AssetDatabase.GetAssetPath(playable.clip)
                            : null,
                        start_frame = Frame(clip.start, fps),
                        end_frame = Frame(clip.end, fps),
                        placeholder = playable != null && playable.clip != null &&
                            playable.clip.name.StartsWith(
                                "CSA_PLACEHOLDER_", StringComparison.Ordinal
                            ),
                    });
                }
                continue;
            }

            actorBinding = StripPrefix(track.name, AudioTrackPrefix);
            if (actorBinding != null && track is AudioTrack)
            {
                foreach (TimelineClip clip in track.GetClips())
                {
                    string cueId = StripPrefix(clip.displayName, DialogueClipPrefix);
                    if (cueId == null)
                    {
                        continue;
                    }
                    AudioPlayableAsset playable = clip.asset as AudioPlayableAsset;
                    audio.Add(new RealizedSection {
                        semantic_id = cueId,
                        actor_binding_id = actorBinding,
                        asset_ref = playable != null && playable.clip != null
                            ? AssetDatabase.GetAssetPath(playable.clip)
                            : null,
                        start_frame = Frame(clip.start, fps),
                        end_frame = Frame(clip.end, fps),
                        placeholder = false,
                    });
                }
                continue;
            }

            if (track is ActivationTrack)
            {
                GameObject cameraObject = director.GetGenericBinding(track) as GameObject;
                Camera camera = cameraObject != null
                    ? cameraObject.GetComponent<Camera>()
                    : null;
                if (camera == null)
                {
                    continue;
                }
                string cutId = StripPrefix(track.name, CameraTrackPrefix);
                if (cutId == null)
                {
                    throw new InvalidOperationException(
                        "Unmapped native camera ActivationTrack: " + track.name
                    );
                }
                TimelineClip clip = track.GetClips().SingleOrDefault();
                SemanticCamera cut = scene.camera_cuts.FirstOrDefault(item => item.cut_id == cutId);
                if (clip == null || cut == null)
                {
                    throw new InvalidOperationException(
                        "Unknown or empty CutSceneAI camera track: " + track.name
                    );
                }
                cut.start_frame = Frame(clip.start, fps);
                cut.end_frame = Frame(clip.end, fps);
                cut.lens_mm = camera.focalLength;
                if (!cameraIds.Add(cutId))
                {
                    throw new InvalidOperationException(
                        "Duplicate CutSceneAI camera track: " + track.name
                    );
                }
            }
        }
        scene.camera_cuts = scene.camera_cuts
            .Where(item => cameraIds.Contains(item.cut_id))
            .ToArray();
    }

    private static void ExportReadbackInternal(Plan plan)
    {
        TimelineSemantics resultSemantics = null;
        List<SemanticScene> actualScenes = new List<SemanticScene>();
        List<RealizedSection> animations = new List<RealizedSection>();
        List<RealizedSection> audio = new List<RealizedSection>();
        List<string> timelinePaths = new List<string>();

        foreach (ScenePlan scenePlan in plan.sequences)
        {
            TimelineAsset timeline = AssetDatabase.LoadAssetAtPath<TimelineAsset>(
                scenePlan.timeline_asset_path
            );
            if (timeline == null)
            {
                throw new InvalidOperationException(
                    "Generated Timeline asset is missing: " + scenePlan.timeline_asset_path
                );
            }
            EditorSceneManager.OpenScene(scenePlan.scene_asset_path, OpenSceneMode.Single);
            PlayableDirector director = UnityEngine.Object
                .FindObjectsByType<PlayableDirector>(FindObjectsSortMode.None)
                .SingleOrDefault(item => item.playableAsset == timeline);
            if (director == null)
            {
                throw new InvalidOperationException(
                    "Generated Scene has no PlayableDirector for " +
                    scenePlan.timeline_asset_path
                );
            }
            TimelineSemantics stored = LoadAttachedSemantics(timeline);
            int actualFps = TimelineFps(timeline);
            stored.fps = actualFps;
            if (resultSemantics == null)
            {
                resultSemantics = stored;
            }
            else if (resultSemantics.cir_fingerprint_sha256 != stored.cir_fingerprint_sha256)
            {
                throw new InvalidOperationException(
                    "Generated Timelines do not carry one identical CIR fingerprint."
                );
            }
            else if (resultSemantics.fps != stored.fps)
            {
                throw new InvalidOperationException(
                    "Generated Timelines do not share one Timeline frame rate."
                );
            }
            SemanticScene scene = FindSemanticScene(stored, scenePlan.source_scene_id);
            scene.duration_frames = Frame(timeline.duration, actualFps);
            ReadEntities(scene);
            ReadSemanticMarkers(timeline, scene, actualFps);
            ReadTracks(timeline, director, scene, actualFps, animations, audio);
            actualScenes.Add(scene);
            timelinePaths.Add(scenePlan.timeline_asset_path);
        }

        resultSemantics.scenes = actualScenes.ToArray();
        EngineReadback readback = new EngineReadback {
            readback_version = "0.1.0",
            engine = "unity",
            engine_version = Application.unityVersion,
            adapter_version = plan.adapter_version,
            timeline_asset = string.Join(";", timelinePaths),
            semantics = resultSemantics,
            evidence = new ReadbackEvidence {
                animation_sections = animations.ToArray(),
                audio_sections = audio.ToArray(),
            },
            warnings = plan.warnings
                .Select(item => item.code + ": " + item.message)
                .ToArray(),
        };

        string projectRoot = Directory.GetParent(Application.dataPath).FullName;
        string outputDirectory = Path.Combine(projectRoot, "CutSceneAIReadbacks");
        Directory.CreateDirectory(outputDirectory);
        string outputPath = Path.Combine(
            outputDirectory,
            plan.project_id + ".unity.readback.json"
        );
        File.WriteAllText(outputPath, JsonUtility.ToJson(readback, true), Encoding.UTF8);
        Debug.Log("CutSceneAI Unity readback: " + outputPath);
    }
}
"""


def render_unity_editor_script(plan: UnityExportPlan) -> str:
    """Render one deterministic Unity Editor importer and readback exporter."""

    plan_json = json.dumps(
        plan.model_dump(mode="json"), separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    encoded = base64.b64encode(plan_json).decode("ascii")
    return _CS_TEMPLATE.replace("__PLAN_BASE64__", encoded)
