"""Generated by CutSceneAI Unreal Adapter v0.7.0 for Unreal Engine 5.8.0.

Run this file inside Unreal Editor with the Python Editor Script Plugin enabled.
It inventories project Static Meshes without modifying any Content Browser asset.
"""

from hashlib import sha256
import json
from pathlib import Path
import re

import unreal


TOKEN_PATTERN = re.compile(r"[A-Za-z0-9]+")
STOP_WORDS = {
    "asset",
    "assets",
    "game",
    "mesh",
    "model",
    "prop",
    "props",
    "sm",
    "static",
}


def _tokens(value):
    return sorted(
        {
            token.lower()
            for token in TOKEN_PATTERN.findall(value)
            if token.lower() not in STOP_WORDS
        }
    )


def _slug(value):
    slug = "-".join(_tokens(value))
    if not slug:
        return "unreal-asset"
    if not slug[0].isalpha():
        return f"asset-{slug}"
    return slug


def _record(asset_data):
    package_name = str(asset_data.package_name)
    asset_name = str(asset_data.asset_name)
    asset_uri = f"{package_name}.{asset_name}"
    digest = sha256(asset_uri.encode("utf-8")).hexdigest()[:8]
    return {
        "id": f"{_slug(package_name)}-{digest}",
        "name": asset_name,
        "kind": "environment_prop",
        "asset_uri": asset_uri,
        "aliases": [],
        "keywords": _tokens(f"{package_name} {asset_name}"),
        "location_terms": [],
        "priority": 0,
    }


def build_asset_index():
    registry = unreal.AssetRegistryHelpers.get_asset_registry()
    asset_data_items = registry.get_assets_by_path("/Game", True, True) or []
    records = []
    for asset_data in asset_data_items:
        if asset_data.is_redirector() or not asset_data.is_u_asset():
            continue
        class_name = str(asset_data.asset_class_path.asset_name)
        if class_name != "StaticMesh":
            continue
        records.append(_record(asset_data))
    records.sort(key=lambda item: (item["asset_uri"], item["id"]))

    project_file = Path(unreal.Paths.get_project_file_path())
    project_name = project_file.stem or "Unreal Project"
    index = {
        "schema_version": "0.1.0",
        "id": f"{_slug(project_name)}-assets",
        "name": f"{project_name} Static Mesh Assets",
        "target_engine": "Unreal Engine",
        "target_engine_version": "5.8.0",
        "assets": records,
    }

    output_directory = (
        Path(
            unreal.Paths.convert_relative_path_to_full(
                unreal.Paths.project_saved_dir()
            )
        )
        / "CutSceneAI"
    )
    output_directory.mkdir(parents=True, exist_ok=True)
    output_path = output_directory / "unreal-project.asset-index.json"
    output_path.write_text(
        json.dumps(index, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    unreal.log(
        f"CutSceneAI indexed {len(records)} Static Mesh assets -> {output_path}"
    )
    unreal.log_warning(
        "CutSceneAI index entries default to environment_prop. "
        "Curate aliases, location_terms, priority, and environment_set roles before resolving."
    )
    return output_path


if __name__ == "__main__":
    build_asset_index()
