import json

from .models import UnrealExportPlan


_SCRIPT_TEMPLATE = '''"""Generated by CutSceneAI Unreal Adapter v0.1 for Unreal Engine 5.8.0.

Run this file inside Unreal Editor with the Python Editor Script Plugin enabled.
Existing assets are never replaced: remove or rename a conflicting Level Sequence first.
"""

import json

import unreal


PLAN = json.loads(__PLAN_JSON__)
CAMERA_CLASS_PATH = "/Script/CinematicCamera.CineCameraActor"
PLACEHOLDER_CUBE_PATH = "/Engine/BasicShapes/Cube.Cube"


def _vector(data):
    return unreal.Vector(float(data["x"]), float(data["y"]), float(data["z"]))


def _rotator(data):
    return unreal.Quat(
        float(data["x"]),
        float(data["y"]),
        float(data["z"]),
        float(data["w"]),
    ).rotator()


def _set_transform(actor, data):
    actor.set_actor_location(_vector(data["location_cm"]), False, True)
    actor.set_actor_rotation(_rotator(data["rotation"]), True)
    actor.set_actor_scale3d(_vector(data["scale"]))


def _load_class(class_path):
    actor_class = unreal.load_class(None, class_path)
    if actor_class is None:
        raise RuntimeError(f"Unable to load Unreal class: {class_path}")
    return actor_class


def _add_actor(sequence, subsystem, actor):
    binding = subsystem.add_spawnable_from_class(
        sequence, _load_class(actor["actor_class_path"])
    )
    binding.set_display_name(actor["display_name"])
    template = binding.get_object_template()
    if template is None:
        raise RuntimeError(f"Spawnable has no object template: {actor['binding_id']}")
    template.set_actor_label(actor["display_name"])
    _set_transform(template, actor["transform"])

    if actor["kind"] == "environment":
        asset_path = actor["asset_path"] or PLACEHOLDER_CUBE_PATH
        static_mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
        if isinstance(static_mesh, unreal.StaticMesh):
            component = template.get_editor_property("static_mesh_component")
            component.set_static_mesh(static_mesh)
        else:
            unreal.log_warning(f"Static mesh could not be loaded: {asset_path}")
    return binding


def _resolve_camera_actor(sequence, binding, camera):
    unreal.LevelSequenceEditorBlueprintLibrary.force_update()
    binding_id = sequence.get_binding_id(binding)
    bound_objects = unreal.LevelSequenceEditorBlueprintLibrary.get_bound_objects(binding_id)
    camera_actor = next(
        (
            item
            for item in bound_objects
            if isinstance(item, unreal.CineCameraActor)
        ),
        None,
    )
    if camera_actor is None:
        template = binding.get_object_template()
        if isinstance(template, unreal.CineCameraActor):
            camera_actor = template
    if camera_actor is None:
        raise RuntimeError(
            f"Unable to resolve spawned Cine Camera Actor: {camera['binding_id']}"
        )
    return camera_actor


def _set_camera_focal_length(component, lens_mm):
    lens_settings = component.get_editor_property("lens_settings")
    minimum = float(lens_settings.get_editor_property("min_focal_length"))
    maximum = float(lens_settings.get_editor_property("max_focal_length"))
    changed = False
    if lens_mm < minimum:
        lens_settings.set_editor_property("min_focal_length", lens_mm)
        changed = True
    if lens_mm > maximum:
        lens_settings.set_editor_property("max_focal_length", lens_mm)
        changed = True
    if changed:
        component.set_editor_property("lens_settings", lens_settings)
    component.set_editor_property("current_focal_length", lens_mm)


def _add_camera(sequence, subsystem, camera):
    binding = subsystem.add_spawnable_from_class(sequence, _load_class(CAMERA_CLASS_PATH))
    binding.set_display_name(camera["display_name"])
    camera_actor = _resolve_camera_actor(sequence, binding, camera)
    camera_actor.set_actor_label(camera["display_name"])
    _set_transform(camera_actor, camera["transform"])
    component = camera_actor.get_cine_camera_component()
    if component is None:
        raise RuntimeError(
            f"Spawned camera has no Cine Camera Component: {camera['binding_id']}"
        )
    _set_camera_focal_length(component, float(camera["lens_mm"]))
    subsystem.save_default_spawnable_state(binding)
    return binding


def _add_marker(sequence, frame, label, comment):
    marker = unreal.MovieSceneMarkedFrame(
        frame_number=unreal.FrameNumber(int(frame)), label=label
    )
    marker.set_editor_property("comment", comment)
    sequence.add_marked_frame_to_sequence(
        marker, unreal.MovieSceneTimeUnit.DISPLAY_RATE
    )


def _add_performance_markers(sequence, cues):
    for index, cue in enumerate(cues, start=1):
        actor_id = cue["actor_binding_id"].split(":", 1)[-1]
        label = f"PERF {index:02d} {actor_id} {cue['source_beat_id']}"
        comment = json.dumps(
            {
                "motion_prompt": cue["motion_prompt"],
                "motion_style": cue["motion_style"],
                "emotion": cue["emotion"],
                "emotion_intensity": cue["emotion_intensity"],
                "lip_sync": cue["lip_sync"],
                "look_at_binding_id": cue["look_at_binding_id"],
            },
            sort_keys=True,
        )
        _add_marker(sequence, cue["start_frame"], label, comment)
        if cue["dialogue"] is not None and cue["dialogue_start_frame"] is not None:
            _add_marker(
                sequence,
                cue["dialogue_start_frame"],
                f"DIALOGUE {index:02d} {actor_id}",
                cue["dialogue"],
            )


def _create_sequence(scene):
    asset_path = f"{scene['package_path']}/{scene['asset_name']}"
    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        raise RuntimeError(
            f"Refusing to replace existing asset '{asset_path}'. "
            "Delete it intentionally or change the package path."
        )

    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    sequence = asset_tools.create_asset(
        scene["asset_name"],
        scene["package_path"],
        unreal.LevelSequence,
        unreal.LevelSequenceFactoryNew(),
    )
    if sequence is None:
        raise RuntimeError(f"Unable to create Level Sequence: {asset_path}")

    sequence.set_display_rate(unreal.FrameRate(PLAN["source_settings"]["fps"], 1))
    sequence.set_playback_start(0)
    sequence.set_playback_end(int(scene["duration_frames"]))
    unreal.LevelSequenceEditorBlueprintLibrary.open_level_sequence(sequence)
    subsystem = unreal.get_editor_subsystem(unreal.LevelSequenceEditorSubsystem)

    bindings = {}
    for actor in scene["actors"]:
        bindings[actor["binding_id"]] = _add_actor(sequence, subsystem, actor)

    for camera in scene["cameras"]:
        bindings[camera["binding_id"]] = _add_camera(sequence, subsystem, camera)

    camera_cut_track = sequence.add_track(unreal.MovieSceneCameraCutTrack)
    for camera in scene["cameras"]:
        section = camera_cut_track.add_section()
        section.set_range(int(camera["start_frame"]), int(camera["end_frame"]))
        section.set_camera_binding_id(
            sequence.get_binding_id(bindings[camera["binding_id"]])
        )

    _add_performance_markers(sequence, scene["performance_cues"])
    sequence.sort_marked_frames()
    unreal.EditorAssetLibrary.save_loaded_asset(sequence, False)
    unreal.log(f"CutSceneAI created {asset_path}")
    return sequence


def import_plan():
    sequences = [_create_sequence(scene) for scene in PLAN["sequences"]]
    if sequences:
        unreal.LevelSequenceEditorBlueprintLibrary.open_level_sequence(sequences[-1])
    for warning in PLAN["warnings"]:
        unreal.log_warning(f"CutSceneAI [{warning['code']}]: {warning['message']}")
    return sequences


if __name__ == "__main__":
    import_plan()
'''


def render_unreal_import_script(plan: UnrealExportPlan) -> str:
    """Render a self-contained, syntax-valid Unreal Editor Python importer."""

    plan_json = json.dumps(
        plan.model_dump(mode="json"), separators=(",", ":"), sort_keys=True
    )
    return _SCRIPT_TEMPLATE.replace("__PLAN_JSON__", repr(plan_json))
