import json

from .models import UnrealExportPlan


_SCRIPT_TEMPLATE = '''"""Generated by CutSceneAI Unreal Adapter v0.3.0 for Unreal Engine 5.8.0.

Run this file inside Unreal Editor with the Python Editor Script Plugin enabled.
Existing assets are never replaced: remove or rename a conflicting Level Sequence first.
"""

import json

import unreal


PLAN = json.loads(__PLAN_JSON__)
CAMERA_CLASS_PATH = "/Script/CinematicCamera.CineCameraActor"
STATIC_MESH_ACTOR_CLASS_PATH = "/Script/Engine.StaticMeshActor"


def _vector(data):
    return unreal.Vector(float(data["x"]), float(data["y"]), float(data["z"]))


def _rotator(data):
    return unreal.Quat(
        float(data["x"]),
        float(data["y"]),
        float(data["z"]),
        float(data["w"]),
    ).rotator()


def _set_transform(actor, data):
    actor.set_actor_location(_vector(data["location_cm"]), False, True)
    actor.set_actor_rotation(_rotator(data["rotation"]), True)
    actor.set_actor_scale3d(_vector(data["scale"]))


def _load_class(class_path):
    actor_class = unreal.load_class(None, class_path)
    if actor_class is None:
        raise RuntimeError(f"Unable to load Unreal class: {class_path}")
    return actor_class


def _load_static_mesh(asset_path):
    static_mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
    if not isinstance(static_mesh, unreal.StaticMesh):
        raise RuntimeError(f"Static mesh could not be loaded: {asset_path}")
    return static_mesh


def _load_skeletal_mesh(asset_path):
    skeletal_mesh = unreal.EditorAssetLibrary.load_asset(asset_path)
    if not isinstance(skeletal_mesh, unreal.SkeletalMesh):
        raise RuntimeError(f"Skeletal mesh could not be loaded: {asset_path}")
    return skeletal_mesh


def _configure_static_mesh(actor, static_mesh, asset_path):
    component = actor.get_editor_property("static_mesh_component")
    if component is None:
        raise RuntimeError(f"StaticMeshActor has no Static Mesh Component: {asset_path}")
    component.set_static_mesh(static_mesh)


def _configure_skeletal_mesh(actor, skeletal_mesh, asset_path):
    component = actor.get_editor_property("skeletal_mesh_component")
    if component is None:
        raise RuntimeError(
            f"SkeletalMeshActor has no Skeletal Mesh Component: {asset_path}"
        )
    component.set_skeletal_mesh_asset(skeletal_mesh)


def _resolve_live_bound_object(sequence, binding, object_type):
    unreal.LevelSequenceEditorBlueprintLibrary.force_update()
    binding_id = sequence.get_binding_id(binding)
    return next(
        (
            item
            for item in unreal.LevelSequenceEditorBlueprintLibrary.get_bound_objects(
                binding_id
            )
            if isinstance(item, object_type)
        ),
        None,
    )


def _remove_default_transform_tracks(binding):
    for track in binding.find_tracks_by_exact_type(
        unreal.MovieScene3DTransformTrack
    ):
        binding.remove_track(track)


def _configure_static_mesh_spawnable(
    sequence,
    subsystem,
    binding,
    binding_id,
    display_name,
    transform,
    asset_path,
):
    static_mesh = _load_static_mesh(asset_path)
    template = binding.get_object_template()
    live_actor = _resolve_live_bound_object(
        sequence, binding, unreal.StaticMeshActor
    )
    targets = []
    if isinstance(template, unreal.StaticMeshActor):
        targets.append(template)
    if live_actor is not None and live_actor is not template:
        targets.append(live_actor)
    if not targets:
        raise RuntimeError(f"Unable to resolve StaticMeshActor spawnable: {binding_id}")
    for target in targets:
        target.set_actor_label(display_name)
        _set_transform(target, transform)
        _configure_static_mesh(target, static_mesh, asset_path)
    if live_actor is not None:
        subsystem.save_default_spawnable_state(binding)


def _configure_skeletal_mesh_spawnable(
    sequence,
    subsystem,
    binding,
    binding_id,
    display_name,
    transform,
    asset_path,
):
    skeletal_mesh = _load_skeletal_mesh(asset_path)
    template = binding.get_object_template()
    live_actor = _resolve_live_bound_object(
        sequence, binding, unreal.SkeletalMeshActor
    )
    targets = []
    if isinstance(template, unreal.SkeletalMeshActor):
        targets.append(template)
    if live_actor is not None and live_actor is not template:
        targets.append(live_actor)
    if not targets:
        raise RuntimeError(f"Unable to resolve SkeletalMeshActor spawnable: {binding_id}")
    for target in targets:
        target.set_actor_label(display_name)
        _set_transform(target, transform)
        _configure_skeletal_mesh(target, skeletal_mesh, asset_path)
    if live_actor is not None:
        subsystem.save_default_spawnable_state(binding)


def _add_set_piece(sequence, subsystem, set_piece):
    binding = subsystem.add_spawnable_from_class(
        sequence, _load_class(STATIC_MESH_ACTOR_CLASS_PATH)
    )
    binding.set_display_name(set_piece["display_name"])
    _remove_default_transform_tracks(binding)
    _configure_static_mesh_spawnable(
        sequence,
        subsystem,
        binding,
        set_piece["binding_id"],
        set_piece["display_name"],
        set_piece["transform"],
        set_piece["mesh_asset_path"],
    )
    return binding


def _add_actor(sequence, subsystem, actor):
    binding = subsystem.add_spawnable_from_class(
        sequence, _load_class(actor["actor_class_path"])
    )
    binding.set_display_name(actor["display_name"])
    _remove_default_transform_tracks(binding)
    visual = actor["placeholder_visual"]
    asset_path = visual["mesh_asset_path"] if visual else actor["asset_path"]
    if actor["mesh_type"] == "skeletal_mesh":
        if asset_path is None:
            raise RuntimeError(
                f"Skeletal character has no asset path: {actor['binding_id']}"
            )
        _configure_skeletal_mesh_spawnable(
            sequence,
            subsystem,
            binding,
            actor["binding_id"],
            actor["display_name"],
            actor["transform"],
            asset_path,
        )
    elif asset_path is not None:
        _configure_static_mesh_spawnable(
            sequence,
            subsystem,
            binding,
            actor["binding_id"],
            actor["display_name"],
            visual["transform"] if visual else actor["transform"],
            asset_path,
        )
    else:
        template = binding.get_object_template()
        if template is None:
            raise RuntimeError(f"Spawnable has no object template: {actor['binding_id']}")
        template.set_actor_label(actor["display_name"])
        _set_transform(template, actor["transform"])
    return binding


def _set_camera_focal_length(component, lens_mm):
    lens_settings = component.get_editor_property("lens_settings")
    minimum = float(lens_settings.get_editor_property("min_focal_length"))
    maximum = float(lens_settings.get_editor_property("max_focal_length"))
    changed = False
    if lens_mm < minimum:
        lens_settings.set_editor_property("min_focal_length", lens_mm)
        changed = True
    if lens_mm > maximum:
        lens_settings.set_editor_property("max_focal_length", lens_mm)
        changed = True
    if changed:
        component.set_editor_property("lens_settings", lens_settings)
    component.set_editor_property("current_focal_length", lens_mm)


def _add_camera(sequence, subsystem, camera):
    binding = subsystem.add_spawnable_from_class(sequence, _load_class(CAMERA_CLASS_PATH))
    binding.set_display_name(camera["display_name"])
    _remove_default_transform_tracks(binding)
    template = binding.get_object_template()
    live_actor = _resolve_live_bound_object(
        sequence, binding, unreal.CineCameraActor
    )
    targets = []
    if isinstance(template, unreal.CineCameraActor):
        targets.append(template)
    if live_actor is not None and live_actor is not template:
        targets.append(live_actor)
    if not targets:
        raise RuntimeError(
            f"Unable to resolve spawned Cine Camera Actor: {camera['binding_id']}"
        )

    configured_component = False
    for target in targets:
        target.set_actor_label(camera["display_name"])
        _set_transform(target, camera["transform"])
        component = target.get_cine_camera_component()
        if component is not None:
            _set_camera_focal_length(component, float(camera["lens_mm"]))
            configured_component = True

    if not configured_component:
        raise RuntimeError(
            f"Spawned camera has no Cine Camera Component: {camera['binding_id']}"
        )
    if live_actor is not None:
        subsystem.save_default_spawnable_state(binding)
    return binding


def _add_marker(sequence, frame, label, comment):
    marker = unreal.MovieSceneMarkedFrame(
        frame_number=unreal.FrameNumber(int(frame)), label=label
    )
    marker.set_editor_property("comment", comment)
    sequence.add_marked_frame_to_sequence(
        marker, unreal.MovieSceneTimeUnit.DISPLAY_RATE
    )


def _add_performance_markers(sequence, cues):
    for index, cue in enumerate(cues, start=1):
        actor_id = cue["actor_binding_id"].split(":", 1)[-1]
        label = f"PERF {index:02d} {actor_id} {cue['source_beat_id']}"
        comment = json.dumps(
            {
                "motion_prompt": cue["motion_prompt"],
                "motion_style": cue["motion_style"],
                "emotion": cue["emotion"],
                "emotion_intensity": cue["emotion_intensity"],
                "lip_sync": cue["lip_sync"],
                "look_at_binding_id": cue["look_at_binding_id"],
            },
            sort_keys=True,
        )
        _add_marker(sequence, cue["start_frame"], label, comment)
        if cue["dialogue"] is not None and cue["dialogue_start_frame"] is not None:
            _add_marker(
                sequence,
                cue["dialogue_start_frame"],
                f"DIALOGUE {index:02d} {actor_id}",
                cue["dialogue"],
            )


def _create_sequence(scene):
    asset_path = f"{scene['package_path']}/{scene['asset_name']}"
    if unreal.EditorAssetLibrary.does_asset_exist(asset_path):
        raise RuntimeError(
            f"Refusing to replace existing asset '{asset_path}'. "
            "Delete it intentionally or change the package path."
        )

    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    sequence = asset_tools.create_asset(
        scene["asset_name"],
        scene["package_path"],
        unreal.LevelSequence,
        unreal.LevelSequenceFactoryNew(),
    )
    if sequence is None:
        raise RuntimeError(f"Unable to create Level Sequence: {asset_path}")

    sequence.set_display_rate(unreal.FrameRate(PLAN["source_settings"]["fps"], 1))
    sequence.set_playback_start(0)
    sequence.set_playback_end(int(scene["duration_frames"]))
    unreal.LevelSequenceEditorBlueprintLibrary.open_level_sequence(sequence)
    subsystem = unreal.get_editor_subsystem(unreal.LevelSequenceEditorSubsystem)

    bindings = {}
    for set_piece in scene["set_pieces"]:
        bindings[set_piece["binding_id"]] = _add_set_piece(
            sequence, subsystem, set_piece
        )

    for actor in scene["actors"]:
        bindings[actor["binding_id"]] = _add_actor(sequence, subsystem, actor)

    for camera in scene["cameras"]:
        bindings[camera["binding_id"]] = _add_camera(sequence, subsystem, camera)

    camera_cut_track = sequence.add_track(unreal.MovieSceneCameraCutTrack)
    for camera in scene["cameras"]:
        section = camera_cut_track.add_section()
        section.set_range(int(camera["start_frame"]), int(camera["end_frame"]))
        section.set_camera_binding_id(
            sequence.get_binding_id(bindings[camera["binding_id"]])
        )

    _add_performance_markers(sequence, scene["performance_cues"])
    sequence.sort_marked_frames()
    unreal.EditorAssetLibrary.save_loaded_asset(sequence, False)
    unreal.log(f"CutSceneAI created {asset_path}")
    return sequence


def import_plan():
    sequences = [_create_sequence(scene) for scene in PLAN["sequences"]]
    if sequences:
        unreal.LevelSequenceEditorBlueprintLibrary.open_level_sequence(sequences[-1])
    for warning in PLAN["warnings"]:
        unreal.log_warning(f"CutSceneAI [{warning['code']}]: {warning['message']}")
    return sequences


if __name__ == "__main__":
    import_plan()
'''


def render_unreal_import_script(plan: UnrealExportPlan) -> str:
    """Render a self-contained, syntax-valid Unreal Editor Python importer."""

    plan_json = json.dumps(
        plan.model_dump(mode="json"), separators=(",", ":"), sort_keys=True
    )
    return _SCRIPT_TEMPLATE.replace("__PLAN_JSON__", repr(plan_json))
