from .audio import MAX_WAV_BYTES, inspect_wav
from .errors import (
    DialogueAudioError,
    DialogueConfigurationError,
    DialogueError,
    DialogueInputError,
    DialogueOutputError,
    DialogueProviderError,
)
from .models import (
    AudioProvenance,
    DialogueClip,
    DialogueCue,
    DialogueManifest,
    DialogueRenderPlan,
    DialogueSource,
    DialogueWarning,
    SpeechSynthesisRequest,
    VoiceProfile,
    WavMetadata,
)
from .planning import plan_project, seconds_to_frame
from .schema import (
    DIALOGUE_MANIFEST_SCHEMA_ID,
    DIALOGUE_PLAN_SCHEMA_ID,
    JSON_SCHEMA_DIALECT,
    dialogue_manifest_json_schema,
    dialogue_plan_json_schema,
    render_dialogue_manifest_json_schema,
    render_dialogue_plan_json_schema,
    write_dialogue_schemas,
)
from .serialization import (
    render_dialogue_bundle,
    render_dialogue_manifest,
    render_dialogue_plan,
)
from .service import (
    DialogueBundle,
    DialogueEngine,
    RecordedAudioInput,
    SpeechBackend,
    SpeechBackendResult,
    build_recorded_bundle,
)

__all__ = [
    "AudioProvenance",
    "DIALOGUE_MANIFEST_SCHEMA_ID",
    "DIALOGUE_PLAN_SCHEMA_ID",
    "DialogueAudioError",
    "DialogueBundle",
    "DialogueClip",
    "DialogueConfigurationError",
    "DialogueCue",
    "DialogueEngine",
    "DialogueError",
    "DialogueInputError",
    "DialogueManifest",
    "DialogueOutputError",
    "DialogueProviderError",
    "DialogueRenderPlan",
    "DialogueSource",
    "DialogueWarning",
    "JSON_SCHEMA_DIALECT",
    "MAX_WAV_BYTES",
    "RecordedAudioInput",
    "SpeechBackend",
    "SpeechBackendResult",
    "SpeechSynthesisRequest",
    "VoiceProfile",
    "WavMetadata",
    "build_recorded_bundle",
    "dialogue_manifest_json_schema",
    "dialogue_plan_json_schema",
    "inspect_wav",
    "plan_project",
    "render_dialogue_bundle",
    "render_dialogue_manifest",
    "render_dialogue_manifest_json_schema",
    "render_dialogue_plan",
    "render_dialogue_plan_json_schema",
    "seconds_to_frame",
    "write_dialogue_schemas",
]
